name: mokobigbro
favicon: null
layout_spectrum: 0.5456056343391538
typography_spectrum: 0.6823378633707762
title: 'my adventure with audio & food'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8125
  lightness: 0.013467807322740555
  saturation: 0.625
  rhythmicContrast: 0.2851775905583054
purpose: []
